# Title: 
#     Subclass is Reflexive
# Constraint Description: 
#     Any class is rdfs:subClassOf of itself.
# Severity:
#     Warning

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?resource ?label ?value 
WHERE {
    ?resource rdfs:subClassOf ?value ;
        rdfs:label ?label 
    FILTER NOT EXISTS {?entity = ?value}
}
ORDER BY ?resource