name: Test Ontology Changes
on:
  push:
    branches-ignore: [ master ]

env:
  cache-path: build/lib
  artifacts-path: build/artifacts/
  cache-key:  build-cache-dependencies

jobs:
  ontology_test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Restore cached dependencies
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.cache-path }}
          # TODO this should be a file with a list of dependencies, to check if it changes and retrigger the cache
          #key: ${{ env-cache-key}}-${{ hashFiles('**/package-lock.json') }}
          key: ${{ runner.os }}-${{ env.cache-key }}

      # Run the main steps here
      - name: Check for inconsistency with Reasoner
        run: make reason-edit

      - name: Run automated tests and generate reports
        run: make test-edit
        if: always()

      # Save any artifact files produced even if tests fail
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ontology_test_results
          path: ${{ env.artifacts-path }}

      # Save cache even if tests fail and only if a cache wasn't restored
      - name: Save dependencies to cache
        id: save-cache
        uses: actions/cache/save@v3
        if: always() && steps.restore-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.cache-path }}
          key: ${{ runner.os }}-${{ env.cache-key }}